export const CONTAINERS = Object.freeze({
  HEADER: "HEADER",
  GREETING: "GREETING",
  SOCIAL_MEDIA_LINKS: "SOCIAL_MEDIA_LINKS",
  SKILLS_SECTION: "SKILLS_SECTION",
  EDUCATION_INFO: "EDUCATION_INFO",
  WORK_EXPERIENCE: "WORK_EXPERIENCE",
  PROJECTS_GITHUB: "PROJECTS_GITHUB",
  CONTRIBUTIONS_OPEN_SOURCE: "CONTRIBUTIONS_OPEN_SOURCE",
  CONTACT_INFO: "CONTACT_INFO"
});

export const SHOW_CONTAINER = Object.freeze({
  [CONTAINERS.GREETING]: true,
  [CONTAINERS.SOCIAL_MEDIA_LINKS]: true,
  [CONTAINERS.SKILLS_SECTION]: true,
  [CONTAINERS.EDUCATION_INFO]: true,
  [CONTAINERS.WORK_EXPERIENCE]: true,
  [CONTAINERS.PROJECTS_GITHUB]: true,
  [CONTAINERS.CONTACT_INFO]: true,
  [CONTAINERS.CONTRIBUTIONS_OPEN_SOURCE]: true
});
